### ISSUE TITLE
打开http://localhost:3000/报错！！！

### ISSUE THREAD

**Issue by GentleLemon** [WongSaang/chatgpt-ui#166]
500
[HPM] Missing "target" option. Example: {target: "http://www.example.org"}

at createConfig (./node_modules/http-proxy-middleware/dist/config-factory.js:38:15)
at new HttpProxyMiddleware (./node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:138:57)
at createProxyMiddleware (./node_modules/http-proxy-middleware/dist/index.js:16:28)
at ./.nuxt/dev/index.mjs:541:5
at new Promise ()
at Object.handler (./.nuxt/dev/index.mjs:540:9)
at Object.handler (./node_modules/h3/dist/index.mjs:1247:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)
at async Object.ufetch [as localFetch] (./node_modules/unenv/runtime/fetch/i

**Comment by YuZhou23** [comment]
https://github.com/WongSaang/chatgpt-ui/issues/139#issuecomment-1504478002

**Comment by WongSaang** [comment]
https://github.com/WongSaang/chatgpt-ui/issues/139#issuecomment-1504478002

**Comment by GentleLemon** [comment]
thanks, My backend is already running, but it still doesn't work
-----------------------
[HPM] Proxy created: /  -> http://backend                                            17:40:41
[17:40:46] [HPM] Error occurred while proxying request localhost:3000/ to http://backend/ [ENOTFOUND] (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by WongSaang** [comment]
Can you access this address `http://backend/` in your browser?

**Comment by GentleLemon** [comment]
No, I can't open it. My system is macos

**Comment by WongSaang** [comment]
So what is your backend server address? `SERVER_DOMAIN` points to your backend service address, `http://backend` is just an example.

**Comment by GentleLemon** [comment]
127.0.0.1:8000
I see, thanks
