### ISSUE TITLE
web search returns 500 internal server error

### ISSUE THREAD

**Issue by ZeekoZhu** [WongSaang/chatgpt-ui#213]
when web search is enabled, it returns 500 internal server error with empty response content.

here is the log:

```
10.89.2.6 - - [26/May/2023:07:53:05 +0000] "GET /api/chat/prompts/ HTTP/1.0" 200 161 "https://xxxx.com/?new" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
Internal Server Error: /api/conversation/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Exception is not JSON serializable
Warning: gpt-4 may change over time. Returning num tokens assuming gpt-4-0314.
Failed to fetch: 403 Forbidden
```

it seems the request to duckduckgo failed with 403, but I can access duckduckgo via curl on the same server.

**Comment by NandhaKishorM** [comment]
same problem

**Comment by justflymars** [comment]
same problem

**Comment by liangxiaowucai** [comment]
same problem .
How to fix this

**Comment by Freshield** [comment]
same problem
