### ISSUE TITLE
open http://localhost:3000/  error. please tell me the where is the .env file and Ihave not found the file to set SERVER_DOMAIN

### ISSUE THREAD

**Issue by caoshuailian** [WongSaang/chatgpt-ui#243]
[HPM] Missing "target" option. Example: {target: "[http://www.example.org"}](http://www.example.org%22%7D/)

at createConfig (./node_modules/http-proxy-middleware/dist/config-factory.js:38:15)
at new HttpProxyMiddleware (./node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:138:57)
at createProxyMiddleware (./node_modules/http-proxy-middleware/dist/index.js:16:28)
at ./.nuxt/dev/index.mjs:541:5
at new Promise ()
at Object.handler (./.nuxt/dev/index.mjs:540:9)
at Object.handler (./node_modules/h3/dist/index.mjs:1247:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async toNodeHandle (./node_modules/h3/dist/index.mjs:1322:7)

**Comment by caoshuailian** [comment]
I have replaced process.env.SERVER_DOMAIN with http://localhost:8000/ But the result is same
