### ISSUE TITLE
It won't connect to MySQL

### ISSUE THREAD

**Issue by Suleman-Elahi** [WongSaang/chatgpt-ui#27]
```
ubuntu@ip-172-26-12-199:~/chatgpt-ui$ sudo docker-compose up
/snap/docker/2746/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
Recreating chatgpt-ui_backend-wsgi-server_1 ... done
Recreating chatgpt-ui_backend-web-server_1  ... done
Recreating chatgpt-ui_client_1              ... done
Attaching to chatgpt-ui_backend-wsgi-server_1, chatgpt-ui_backend-web-server_1, chatgpt-ui_client_1
backend-web-server_1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
backend-web-server_1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
backend-web-server_1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
backend-web-server_1   | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
backend-web-server_1   | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
backend-web-server_1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
backend-web-server_1   | /docker-entrypoint.sh: Configuration complete; ready for start up
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: using the "epoll" event method
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: nginx/1.22.1
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: built by gcc 11.2.1 20220219 (Alpine 11.2.1_git20220219) 
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: OS: Linux 4.15.0-1021-aws
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:4096
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: start worker processes
backend-web-server_1   | 2023/03/11 11:26:49 [notice] 1#1: start worker process 34
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
backend-wsgi-server_1  |     connection = Database.connect(**conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
backend-wsgi-server_1  |     return Connection(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
backend-wsgi-server_1  |     super().__init__(*args, **kwargs2)
backend-wsgi-server_1  | MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'host.docker.internal' (-2)")
backend-wsgi-server_1  | 
backend-wsgi-server_1  | The above exception was the direct cause of the following exception:
backend-wsgi-server_1  | 
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/app/manage.py", line 22, in <module>
backend-wsgi-server_1  |     main()
backend-wsgi-server_1  |   File "/app/manage.py", line 18, in main
backend-wsgi-server_1  |     execute_from_command_line(sys.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
backend-wsgi-server_1  |     utility.execute()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
backend-wsgi-server_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
backend-wsgi-server_1  |     self.execute(*args, **cmd_options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
backend-wsgi-server_1  |     output = self.handle(*args, **options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped
backend-wsgi-server_1  |     res = handle_func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 97, in handle
backend-wsgi-server_1  |     self.check(databases=[database])
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 475, in check
backend-wsgi-server_1  |     all_issues = checks.run_checks(
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
backend-wsgi-server_1  |     new_errors = check(app_configs=app_configs, databases=databases)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/checks/model_checks.py", line 36, in check_all_models
backend-wsgi-server_1  |     errors.extend(model.check(**kwargs))
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1536, in check
backend-wsgi-server_1  |     *cls._check_indexes(databases),
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1955, in _check_indexes
backend-wsgi-server_1  |     connection.features.supports_expression_indexes
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend-wsgi-server_1  |     res = instance.__dict__[self.name] = self.func(instance)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/features.py", line 371, in supports_expression_indexes
backend-wsgi-server_1  |     not self.connection.mysql_is_mariadb
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend-wsgi-server_1  |     res = instance.__dict__[self.name] = self.func(instance)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 439, in mysql_is_mariadb
backend-wsgi-server_1  |     return "mariadb" in self.mysql_server_info.lower()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend-wsgi-server_1  |     res = instance.__dict__[self.name] = self.func(instance)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 425, in mysql_server_info
backend-wsgi-server_1  |     return self.mysql_server_data["version"]
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
backend-wsgi-server_1  |     res = instance.__dict__[self.name] = self.func(instance)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 399, in mysql_server_data
backend-wsgi-server_1  |     with self.temporary_connection() as cursor:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
backend-wsgi-server_1  |     return next(self.gen)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 694, in temporary_connection
backend-wsgi-server_1  |     with self.cursor() as cursor:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
backend-wsgi-server_1  |     return self._cursor()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
backend-wsgi-server_1  |     self.ensure_connection()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
backend-wsgi-server_1  |     with self.wrap_database_errors:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
backend-wsgi-server_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
backend-wsgi-server_1  |     connection = Database.connect(**conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
backend-wsgi-server_1  |     return Connection(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
backend-wsgi-server_1  |     super().__init__(*args, **kwargs2)
backend-wsgi-server_1  | django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'host.docker.internal' (-2)")
client_1               | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
client_1               | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
client_1               | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
client_1               | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
client_1               | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
client_1               | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
client_1               | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
client_1               | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
client_1               | /docker-entrypoint.sh: Configuration complete; ready for start up
client_1               | 2023/03/11 11:26:50 [notice] 1#1: using the "epoll" event method
client_1               | 2023/03/11 11:26:50 [notice] 1#1: nginx/1.23.3
client_1               | 2023/03/11 11:26:50 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
client_1               | 2023/03/11 11:26:50 [notice] 1#1: OS: Linux 4.15.0-1021-aws
client_1               | 2023/03/11 11:26:50 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:4096
client_1               | 2023/03/11 11:26:50 [notice] 1#1: start worker processes
client_1               | 2023/03/11 11:26:50 [notice] 1#1: start worker process 34
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
backend-wsgi-server_1  |     connection = Database.connect(**conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
backend-wsgi-server_1  |     return Connection(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
backend-wsgi-server_1  |     super().__init__(*args, **kwargs2)
backend-wsgi-server_1  | MySQLdb.OperationalError: (2005, "Unknown MySQL server host 'host.docker.internal' (-2)")
backend-wsgi-server_1  | 
backend-wsgi-server_1  | The above exception was the direct cause of the following exception:
backend-wsgi-server_1  | 
backend-wsgi-server_1  | Traceback (most recent call last):
backend-wsgi-server_1  |   File "/app/manage.py", line 22, in <module>
backend-wsgi-server_1  |     main()
backend-wsgi-server_1  |   File "/app/manage.py", line 18, in main
backend-wsgi-server_1  |     execute_from_command_line(sys.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
backend-wsgi-server_1  |     utility.execute()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
backend-wsgi-server_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
backend-wsgi-server_1  |     self.execute(*args, **cmd_options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
backend-wsgi-server_1  |     return super().execute(*args, **options)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 447, in execute
backend-wsgi-server_1  |     self.check_migrations()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 564, in check_migrations
backend-wsgi-server_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 18, in __init__
backend-wsgi-server_1  |     self.loader = MigrationLoader(self.connection)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 58, in __init__
backend-wsgi-server_1  |     self.build_graph()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/loader.py", line 235, in build_graph
backend-wsgi-server_1  |     self.applied_migrations = recorder.applied_migrations()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
backend-wsgi-server_1  |     if self.has_table():
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/recorder.py", line 57, in has_table
backend-wsgi-server_1  |     with self.connection.cursor() as cursor:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 323, in cursor
backend-wsgi-server_1  |     return self._cursor()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 299, in _cursor
backend-wsgi-server_1  |     self.ensure_connection()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 281, in ensure_connection
backend-wsgi-server_1  |     with self.wrap_database_errors:
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
backend-wsgi-server_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 282, in ensure_connection
backend-wsgi-server_1  |     self.connect()
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 263, in connect
backend-wsgi-server_1  |     self.connection = self.get_new_connection(conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
backend-wsgi-server_1  |     return func(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/django/db/backends/mysql/base.py", line 247, in get_new_connection
backend-wsgi-server_1  |     connection = Database.connect(**conn_params)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 123, in Connect
backend-wsgi-server_1  |     return Connection(*args, **kwargs)
backend-wsgi-server_1  |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 185, in __init__
backend-wsgi-server_1  |     super().__init__(*args, **kwargs2)
backend-wsgi-server_1  | django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'host.docker.internal' (-2)")
backend-wsgi-server_1  | [2023-03-11 11:26:51 +0000] [1] [INFO] Starting gunicorn 20.1.0
backend-wsgi-server_1  | [2023-03-11 11:26:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
backend-wsgi-server_1  | [2023-03-11 11:26:51 +0000] [1] [INFO] Using worker: sync
backend-wsgi-server_1  | [2023-03-11 11:26:51 +0000] [8] [INFO] Booting worker with pid: 
```
After so many attempts, it refuses to connect to MySQL running on my hist machine. I tried with local IP, localhost, and the sever IP. None of them would work.

**Comment by WongSaang** [comment]
"127.0.0.1" or "localhost" both point to the container internally. You can try using the host machine's internal IP address instead. You can check the internal IP address of the host machine using the command "ifconfig".

**Comment by Suleman-Elahi** [comment]
Thanks. It helped.
